title: SitongCHEN's Homepage
page-top-title: Sitong Chen
top-section-bg-text: I am a driven Biomedical Engineering student at Southern University of Science and Technology, my current work focuses on multimodal neural decoding, EEG signal analysis, I am passionate about exploring more on BCI technologies to restore autonomy for individuals with neurological disorders, and democratizing neurotechnology for real-world impact.
